### ISSUE TITLE
Gerrit initialization failed

### ISSUE THREAD

**Issue by matclab** [GerritCodeReview/docker-gerrit#1]
When doing `docker-compose up gerrit` after having uncommented the init entry point I get:
```
gerrit_1      | Exception in thread "main" com.google.gwtorm.server.OrmException: Cannot initialize schema
gerrit_1      |         at com.google.gerrit.server.schema.SchemaUpdater.update(SchemaUpdater.java:110)
gerrit_1      |         at com.google.gerrit.pgm.init.BaseInit$SiteRun.upgradeSchema(BaseInit.java:386)
gerrit_1      |         at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:143)
gerrit_1      |         at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gerrit_1      |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gerrit_1      |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gerrit_1      |         at java.lang.reflect.Method.invoke(Method.java:498)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:204)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:108)
gerrit_1      |         at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
gerrit_1      |         at Main.main(Main.java:24)
gerrit_1      | Caused by: java.io.IOException: Failed to initialize All-Projects refs:
gerrit_1      | BatchRefUpdate[
gerrit_1      |   CREATE: 0000000000000000000000000000000000000000 019a94b5a743b61fe573728ca83c4ef3c9e8c717 refs/meta/config  (LOCK_FAILURE)
gerrit_1      | ]
gerrit_1      |         at com.google.gerrit.server.schema.AllProjectsCreator.execute(AllProjectsCreator.java:241)
gerrit_1      |         at com.google.gerrit.server.schema.AllProjectsCreator.initAllProjects(AllProjectsCreator.java:203)
gerrit_1      |         at com.google.gerrit.server.schema.AllProjectsCreator.create(AllProjectsCreator.java:120)
gerrit_1      |         at com.google.gerrit.server.schema.SchemaCreator.create(SchemaCreator.java:93)
gerrit_1      |         at com.google.gerrit.server.schema.SchemaUpdater.update(SchemaUpdater.java:108)
gerrit_1      |         ... 11 more
```
If I erase `All-Projects.git/` and  `All-Users.git/ `, the the init phase comes to end with the message `Initialized /var/gerrit`.
However once logged in as `gerritadmin`, I can not see any admin feature (no button or link to create a project,…).
Moreover `system_config` table contains only:
```
 register_email_private_key |  site_path  | admin_group_id | anonymous_group_id | registered_gr
oup_id | wild_project_name | batch_users_group_id | owner_group_id | admin_group_uuid | batch_u
sers_group_uuid | singleton 
----------------------------+-------------+----------------+--------------------+--------------
-------+-------------------+----------------------+----------------+------------------+--------
----------------+-----------
                            | /var/gerrit |                |                    |              
       |                   |                      |                |                  |        
                | X
``` 
which seems strange to me.

**Comment by lucamilanesio** [comment]
Why don't you post your query on the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss)?

**Comment by matclab** [comment]
Perhaps something similar with [gerrit issue 2218](https://bugs.chromium.org/p/gerrit/issues/detail?id=2218)

After some investigation, it appears that group uuids in All-Projects/groups and in the account_groups table do not match.
I solve the problem by tweaking the database to put the good id and uuid in  the following tables:
- `system_config`.{admin_group_id, admin_group_uuid, batch_usbatch_users_group_iders_group_uuid,}
- `account_groups`
and adding the id 1000000 as an administrator user in `account_group_members` table.

Hope it may help other people…

**Comment by matclab** [comment]
Note that [gerrit issue 1768](https://bugs.chromium.org/p/gerrit/issues/detail?id=1768) helps me to find about content of `All-Projects/groups `

**Comment by matclab** [comment]
@lucamilanesio I'll do it. Thanks for the direction.

**Comment by matclab** [comment]
In fact, the README ask to initialize gerrit, by uncommenting the docker-compose entrypoint, whereas the DockerFile does the initialisation. I guess it is not a good idea to do several initialisations.

@lucamilanesio shall I reopen the bug report ?

**Comment by matclab** [comment]
Ok, my problem was caused by my use of docker named bind-mounted volumes (see  https://docs.docker.com/engine/admin/volumes/bind-mounts/#mounting-into-a-non-empty-directory-on-the-container)

>    if you bind-mount into a non-empty directory on the container, the directory’s existing contents will be obscured by the bind mount.

Replacing the bind mounted volumes by local volumes and deleting named volumes make things work as expected.
