### ISSUE TITLE
how to use notedb(NoteDb will be used and will be the only one database in gerrit 3.x)

### ISSUE THREAD

**Issue by learningendless** [GerritCodeReview/docker-gerrit#16]
How to use notedb instead of reviewdb? Just change the database configuration in gerrit.config?
According to web https://hub.docker.com/r/gerritcodereview/gerrit, you preffer the integrated H2 database to postgresql(the former version).  Before, I use postgresql, do you advise me to change to H2?

**Comment by learningendless** [comment]
gerrit notedb info : https://gerrit-documentation.storage.googleapis.com/Documentation/2.16/note-db.html

**Comment by lucamilanesio** [comment]
This is only a mirror of the project on [Gerrit-Review](https://gerrit.googlesource.com/docker-gerrit). Can you please post your question on the [Gerrit Mailing list?](https://groups.google.com/forum/#!forum/repo-discuss)
