### ISSUE TITLE
No host ssh keys found under /var/gerrit/etc

### ISSUE THREAD

**Issue by Abhishekqwerty** [GerritCodeReview/docker-gerrit#18]
When running gerrit on docker container. I am getting ssh keys not found in /var/gerrit/etc directory. Follwing is the screen shot of the log.
Can some one tell me which ssh keys are required.
![gerrit_log_snap](https://user-images.githubusercontent.com/13993954/54410266-b1d3b000-4710-11e9-8c45-d4aff2feffd1.JPG)

**Comment by lucamilanesio** [comment]
This is only a mirror of the project on [Gerrit-Review](https://gerrit.googlesource.com/docker-gerrit). Can you please post your question on the [Gerrit Mailing list?](https://groups.google.com/forum/#!forum/repo-discuss)
