### ISSUE TITLE
v3.0.0-rc2 failure to work on ubuntu 18

### ISSUE THREAD

**Issue by evenflows** [GerritCodeReview/docker-gerrit#20]
builds fine and runs however browser keeps returning javascript not enabled even though it is.
you can access http://gerrit/login, but its missing a lot of stuff.
nothing else works, httpd log shows 200.

broke my head, decided to downgrade to v3.0.0-rc1. works.

thanks

**Comment by dpursehouse** [comment]
This is a known regression in 3.0.0-rc2 that was fixed in 3.0.0-rc3.

See https://bugs.chromium.org/p/gerrit/issues/detail?id=10803
