### ISSUE TITLE
No SSH keys under /var/gerrit/etc

### ISSUE THREAD

**Issue by houan77217** [GerritCodeReview/docker-gerrit#6]
Hi All,

When I follow "Using Gerrit in production" and mount local folder to /var/gerrit/etc in container.
I will got error about SSH Key not found in /var/gerrit/etc at "docker-compose up gerrit" step.
I think it's because gerrit init before mount volumes.

**Comment by mbhagavathula** [comment]
gerrit_1      | 1) No SSH keys under /var/gerrit/etc
gerrit_1      |   while locating com.google.gerrit.sshd.HostKeyProvider
gerrit_1      |   at com.google.gerrit.sshd.SshHostKeyModule.configure(SshHostKeyModule.java:25)
gerrit_1      |   while locating org.apache.sshd.common.keyprovider.KeyPairProvider
gerrit_1      |     for the 6th parameter of com.google.gerrit.sshd.DatabasePubKeyAuth.<init>(DatabasePubKeyAuth.java:72)
gerrit_1      |   while locating com.google.gerrit.sshd.DatabasePubKeyAuth
gerrit_1      |     for the 1st parameter of com.google.gerrit.sshd.CachingPublicKeyAuthenticator.<init>(CachingPublicKeyAuthenticator.java:26)
gerrit_1      |   at com.google.gerrit.sshd.CachingPublicKeyAuthenticator.class(CachingPublicKeyAuthenticator.java:26)
gerrit_1      |   while locating com.google.gerrit.sshd.CachingPublicKeyAuthenticator
